import { NextRequest, NextResponse } from "next/server";

export const runtime = "edge";

/** One row of state-level data */
export interface IndiaDataRow {
  state: string;
  value: number;
}

export interface IndiaDataResponse {
  indicatorId: string;
  indicatorName: string;
  unit: string;
  year: number;
  rows: IndiaDataRow[];
  source: string;
}

// ── Curated India state datasets ────────────────────────────────────────
// Sources: Census 2011/2021, NFHS-5 (2019-21), MOSPI GSDP 2022-23,
//          NITI Aayog SDG Index 2023-24, PLFS 2022-23, RBI, NCRB, FSI

const DATASETS: Record<string, IndiaDataResponse> = {

  // ── Economy ─────────────────────────────────────────────────────────
  "india-gsdp": {
    indicatorId: "india-gsdp",
    indicatorName: "GSDP (State GDP)",
    unit: "USD B",
    year: 2023,
    source: "MOSPI / CSO 2022-23",
    rows: [
      { state: "Maharashtra",        value: 480 },
      { state: "Tamil Nadu",         value: 320 },
      { state: "Gujarat",            value: 310 },
      { state: "Karnataka",          value: 295 },
      { state: "Uttar Pradesh",      value: 282 },
      { state: "West Bengal",        value: 218 },
      { state: "Rajasthan",          value: 198 },
      { state: "Andhra Pradesh",     value: 182 },
      { state: "Telangana",          value: 179 },
      { state: "Madhya Pradesh",     value: 172 },
      { state: "NCT of Delhi",       value: 152 },
      { state: "Kerala",             value: 138 },
      { state: "Haryana",            value: 133 },
      { state: "Bihar",              value: 107 },
      { state: "Punjab",             value: 93 },
      { state: "Odisha",             value: 100 },
      { state: "Chhattisgarh",       value: 64 },
      { state: "Assam",              value: 62 },
      { state: "Jharkhand",          value: 54 },
      { state: "Uttarakhand",        value: 48 },
      { state: "Himachal Pradesh",   value: 32 },
      { state: "Jammu & Kashmir",    value: 30 },
      { state: "Goa",                value: 14 },
      { state: "Tripura",            value: 12 },
      { state: "Chandigarh",         value: 12 },
      { state: "Meghalaya",          value: 7.5 },
      { state: "Manipur",            value: 5.5 },
      { state: "Puducherry",         value: 5.2 },
      { state: "Nagaland",           value: 5.0 },
      { state: "Arunanchal Pradesh", value: 4.5 },
      { state: "Mizoram",            value: 4.0 },
      { state: "Sikkim",             value: 5.2 },
    ],
  },

  "india-gdp-per-capita": {
    indicatorId: "india-gdp-per-capita",
    indicatorName: "GDP per Capita",
    unit: "USD / person",
    year: 2023,
    source: "MOSPI / CSO 2022-23",
    rows: [
      { state: "Sikkim",             value: 8200 },
      { state: "Goa",                value: 7800 },
      { state: "NCT of Delhi",       value: 6600 },
      { state: "Telangana",          value: 4300 },
      { state: "Haryana",            value: 4100 },
      { state: "Karnataka",          value: 3900 },
      { state: "Tamil Nadu",         value: 3800 },
      { state: "Gujarat",            value: 3700 },
      { state: "Himachal Pradesh",   value: 3600 },
      { state: "Maharashtra",        value: 3500 },
      { state: "Punjab",             value: 2900 },
      { state: "Kerala",             value: 3300 },
      { state: "Uttarakhand",        value: 3200 },
      { state: "Andhra Pradesh",     value: 3000 },
      { state: "Chandigarh",         value: 5800 },
      { state: "Puducherry",         value: 3200 },
      { state: "Rajasthan",          value: 2200 },
      { state: "Odisha",             value: 2100 },
      { state: "Jammu & Kashmir",    value: 2000 },
      { state: "Chhattisgarh",       value: 1900 },
      { state: "West Bengal",        value: 2100 },
      { state: "Madhya Pradesh",     value: 1900 },
      { state: "Assam",              value: 1600 },
      { state: "Tripura",            value: 2100 },
      { state: "Nagaland",           value: 2100 },
      { state: "Mizoram",            value: 2500 },
      { state: "Meghalaya",          value: 1900 },
      { state: "Arunanchal Pradesh", value: 2500 },
      { state: "Manipur",            value: 1500 },
      { state: "Jharkhand",          value: 1300 },
      { state: "Uttar Pradesh",      value: 1100 },
      { state: "Bihar",              value: 800 },
    ],
  },

  "india-poverty": {
    indicatorId: "india-poverty",
    indicatorName: "Poverty Rate",
    unit: "%",
    year: 2022,
    source: "NITI Aayog MPI 2022",
    rows: [
      { state: "Bihar",              value: 33.7 },
      { state: "Jharkhand",          value: 28.8 },
      { state: "Uttar Pradesh",      value: 22.9 },
      { state: "Madhya Pradesh",     value: 20.6 },
      { state: "Meghalaya",          value: 27.0 },
      { state: "Assam",              value: 19.7 },
      { state: "Chhattisgarh",       value: 24.9 },
      { state: "Arunanchal Pradesh", value: 24.3 },
      { state: "Odisha",             value: 16.2 },
      { state: "Manipur",            value: 17.9 },
      { state: "Nagaland",           value: 15.4 },
      { state: "Tripura",            value: 13.1 },
      { state: "West Bengal",        value: 11.9 },
      { state: "Rajasthan",          value: 10.7 },
      { state: "Uttarakhand",        value: 9.7 },
      { state: "Mizoram",            value: 9.8 },
      { state: "Maharashtra",        value: 9.5 },
      { state: "Haryana",            value: 7.0 },
      { state: "Gujarat",            value: 8.5 },
      { state: "Himachal Pradesh",   value: 7.6 },
      { state: "Karnataka",          value: 7.6 },
      { state: "Andhra Pradesh",     value: 6.1 },
      { state: "Telangana",          value: 5.9 },
      { state: "Tamil Nadu",         value: 4.9 },
      { state: "Punjab",             value: 4.8 },
      { state: "NCT of Delhi",       value: 4.8 },
      { state: "Jammu & Kashmir",    value: 4.8 },
      { state: "Goa",                value: 3.8 },
      { state: "Sikkim",             value: 2.5 },
      { state: "Puducherry",         value: 1.0 },
      { state: "Kerala",             value: 0.7 },
    ],
  },

  "india-unemployment": {
    indicatorId: "india-unemployment",
    indicatorName: "Unemployment Rate",
    unit: "%",
    year: 2023,
    source: "PLFS 2022-23 (Annual)",
    rows: [
      { state: "Jammu & Kashmir",    value: 12.5 },
      { state: "Nagaland",           value: 10.9 },
      { state: "Tripura",            value: 9.8 },
      { state: "Manipur",            value: 8.4 },
      { state: "Haryana",            value: 7.8 },
      { state: "Kerala",             value: 7.4 },
      { state: "Punjab",             value: 7.5 },
      { state: "Puducherry",         value: 7.2 },
      { state: "West Bengal",        value: 5.7 },
      { state: "Jharkhand",          value: 5.9 },
      { state: "Assam",              value: 5.8 },
      { state: "NCT of Delhi",       value: 5.3 },
      { state: "Andhra Pradesh",     value: 5.3 },
      { state: "Himachal Pradesh",   value: 4.9 },
      { state: "Meghalaya",          value: 5.2 },
      { state: "Uttarakhand",        value: 4.3 },
      { state: "Arunanchal Pradesh", value: 4.4 },
      { state: "Tamil Nadu",         value: 4.0 },
      { state: "Goa",                value: 4.1 },
      { state: "Bihar",              value: 4.5 },
      { state: "Uttar Pradesh",      value: 3.8 },
      { state: "Mizoram",            value: 3.4 },
      { state: "Karnataka",          value: 3.2 },
      { state: "Sikkim",             value: 3.1 },
      { state: "Telangana",          value: 3.1 },
      { state: "Odisha",             value: 2.7 },
      { state: "Maharashtra",        value: 2.9 },
      { state: "Rajasthan",          value: 3.0 },
      { state: "Madhya Pradesh",     value: 2.3 },
      { state: "Chhattisgarh",       value: 2.1 },
      { state: "Gujarat",            value: 1.8 },
    ],
  },

  "india-agriculture-share": {
    indicatorId: "india-agriculture-share",
    indicatorName: "Agriculture Share of GSDP",
    unit: "% of GSDP",
    year: 2022,
    source: "RBI State Finances 2022",
    rows: [
      { state: "Punjab",             value: 28.4 },
      { state: "Madhya Pradesh",     value: 29.1 },
      { state: "Nagaland",           value: 24.0 },
      { state: "Uttar Pradesh",      value: 24.8 },
      { state: "Andhra Pradesh",     value: 24.0 },
      { state: "Rajasthan",          value: 22.5 },
      { state: "Manipur",            value: 21.5 },
      { state: "Mizoram",            value: 20.0 },
      { state: "Chhattisgarh",       value: 20.4 },
      { state: "Bihar",              value: 19.4 },
      { state: "Odisha",             value: 18.3 },
      { state: "Tripura",            value: 18.6 },
      { state: "Haryana",            value: 18.0 },
      { state: "West Bengal",        value: 17.1 },
      { state: "Telangana",          value: 16.4 },
      { state: "Meghalaya",          value: 15.8 },
      { state: "Himachal Pradesh",   value: 15.2 },
      { state: "Karnataka",          value: 14.5 },
      { state: "Gujarat",            value: 13.8 },
      { state: "Jharkhand",          value: 13.4 },
      { state: "Arunanchal Pradesh", value: 12.8 },
      { state: "Maharashtra",        value: 12.4 },
      { state: "Uttarakhand",        value: 11.2 },
      { state: "Kerala",             value: 10.9 },
      { state: "Tamil Nadu",         value: 9.6 },
      { state: "Assam",              value: 26.7 },
      { state: "Sikkim",             value: 13.0 },
      { state: "Jammu & Kashmir",    value: 16.0 },
      { state: "Goa",                value: 2.5 },
      { state: "NCT of Delhi",       value: 0.4 },
    ],
  },

  // ── Population ───────────────────────────────────────────────────────
  "india-population": {
    indicatorId: "india-population",
    indicatorName: "Population (Estimated)",
    unit: "M people",
    year: 2023,
    source: "Census 2011 + Projected",
    rows: [
      { state: "Uttar Pradesh",      value: 235.7 },
      { state: "Bihar",              value: 128.5 },
      { state: "Maharashtra",        value: 126.4 },
      { state: "West Bengal",        value: 101.5 },
      { state: "Madhya Pradesh",     value: 90.0 },
      { state: "Rajasthan",          value: 84.0 },
      { state: "Tamil Nadu",         value: 78.8 },
      { state: "Karnataka",          value: 68.0 },
      { state: "Gujarat",            value: 72.5 },
      { state: "Andhra Pradesh",     value: 55.0 },
      { state: "Odisha",             value: 47.5 },
      { state: "Telangana",          value: 39.5 },
      { state: "Jharkhand",          value: 39.5 },
      { state: "Assam",              value: 36.5 },
      { state: "Kerala",             value: 36.0 },
      { state: "NCT of Delhi",       value: 33.8 },
      { state: "Punjab",             value: 31.0 },
      { state: "Chhattisgarh",       value: 31.0 },
      { state: "Haryana",            value: 30.5 },
      { state: "Jammu & Kashmir",    value: 14.2 },
      { state: "Uttarakhand",        value: 11.8 },
      { state: "Himachal Pradesh",   value: 7.8 },
      { state: "Tripura",            value: 4.2 },
      { state: "Meghalaya",          value: 3.6 },
      { state: "Manipur",            value: 3.2 },
      { state: "Nagaland",           value: 2.3 },
      { state: "Goa",                value: 1.7 },
      { state: "Arunanchal Pradesh", value: 1.7 },
      { state: "Puducherry",         value: 1.7 },
      { state: "Mizoram",            value: 1.3 },
      { state: "Chandigarh",         value: 1.2 },
      { state: "Sikkim",             value: 0.7 },
      { state: "Andaman & Nicobar Island", value: 0.4 },
    ],
  },

  "india-density": {
    indicatorId: "india-density",
    indicatorName: "Population Density",
    unit: "people / km²",
    year: 2011,
    source: "Census 2011",
    rows: [
      { state: "NCT of Delhi",       value: 11297 },
      { state: "Chandigarh",         value: 9252 },
      { state: "Puducherry",         value: 2598 },
      { state: "Daman & Diu",        value: 2169 },
      { state: "Lakshadweep",        value: 2013 },
      { state: "Bihar",              value: 1102 },
      { state: "West Bengal",        value: 1029 },
      { state: "Kerala",             value: 859 },
      { state: "Uttar Pradesh",      value: 829 },
      { state: "Haryana",            value: 573 },
      { state: "Tamil Nadu",         value: 555 },
      { state: "Punjab",             value: 551 },
      { state: "Jharkhand",          value: 414 },
      { state: "Assam",              value: 397 },
      { state: "Goa",                value: 394 },
      { state: "Maharashtra",        value: 365 },
      { state: "Tripura",            value: 350 },
      { state: "Andhra Pradesh",     value: 308 },
      { state: "Karnataka",          value: 319 },
      { state: "Gujarat",            value: 308 },
      { state: "Odisha",             value: 269 },
      { state: "Madhya Pradesh",     value: 236 },
      { state: "Rajasthan",          value: 200 },
      { state: "Uttarakhand",        value: 189 },
      { state: "Chhattisgarh",       value: 189 },
      { state: "Meghalaya",          value: 132 },
      { state: "Himachal Pradesh",   value: 123 },
      { state: "Jammu & Kashmir",    value: 124 },
      { state: "Manipur",            value: 122 },
      { state: "Nagaland",           value: 119 },
      { state: "Sikkim",             value: 86 },
      { state: "Mizoram",            value: 52 },
      { state: "Andaman & Nicobar Island", value: 46 },
      { state: "Arunanchal Pradesh", value: 17 },
    ],
  },

  "india-urban-population": {
    indicatorId: "india-urban-population",
    indicatorName: "Urban Population",
    unit: "%",
    year: 2011,
    source: "Census 2011",
    rows: [
      { state: "NCT of Delhi",       value: 97.5 },
      { state: "Chandigarh",         value: 97.3 },
      { state: "Puducherry",         value: 68.3 },
      { state: "Goa",                value: 62.2 },
      { state: "Mizoram",            value: 52.1 },
      { state: "Tamil Nadu",         value: 48.4 },
      { state: "Kerala",             value: 47.7 },
      { state: "Maharashtra",        value: 45.2 },
      { state: "Gujarat",            value: 42.6 },
      { state: "Telangana",          value: 38.9 },
      { state: "Karnataka",          value: 38.6 },
      { state: "Punjab",             value: 37.5 },
      { state: "Andhra Pradesh",     value: 33.5 },
      { state: "West Bengal",        value: 31.9 },
      { state: "Uttarakhand",        value: 30.6 },
      { state: "Nagaland",           value: 28.9 },
      { state: "Jammu & Kashmir",    value: 27.4 },
      { state: "Tripura",            value: 26.2 },
      { state: "Rajasthan",          value: 24.9 },
      { state: "Jharkhand",          value: 24.1 },
      { state: "Sikkim",             value: 25.0 },
      { state: "Arunanchal Pradesh", value: 22.7 },
      { state: "Uttar Pradesh",      value: 22.3 },
      { state: "Meghalaya",          value: 20.1 },
      { state: "Madhya Pradesh",     value: 27.6 },
      { state: "Manipur",            value: 32.5 },
      { state: "Haryana",            value: 34.9 },
      { state: "Odisha",             value: 16.7 },
      { state: "Chhattisgarh",       value: 23.2 },
      { state: "Assam",              value: 14.1 },
      { state: "Himachal Pradesh",   value: 10.0 },
      { state: "Bihar",              value: 11.3 },
    ],
  },

  "india-sex-ratio": {
    indicatorId: "india-sex-ratio",
    indicatorName: "Sex Ratio",
    unit: "females / 1,000 males",
    year: 2011,
    source: "Census 2011",
    rows: [
      { state: "Kerala",             value: 1084 },
      { state: "Puducherry",         value: 1037 },
      { state: "Tamil Nadu",         value: 996 },
      { state: "Andhra Pradesh",     value: 993 },
      { state: "Chhattisgarh",       value: 991 },
      { state: "Meghalaya",          value: 989 },
      { state: "Manipur",            value: 987 },
      { state: "Odisha",             value: 979 },
      { state: "Tripura",            value: 960 },
      { state: "Mizoram",            value: 976 },
      { state: "Himachal Pradesh",   value: 972 },
      { state: "Uttarakhand",        value: 963 },
      { state: "Karnataka",          value: 973 },
      { state: "West Bengal",        value: 950 },
      { state: "Assam",              value: 958 },
      { state: "Telangana",          value: 988 },
      { state: "Gujarat",            value: 919 },
      { state: "Bihar",              value: 918 },
      { state: "Uttar Pradesh",      value: 912 },
      { state: "Maharashtra",        value: 929 },
      { state: "Punjab",             value: 895 },
      { state: "Haryana",            value: 879 },
      { state: "Rajasthan",          value: 928 },
      { state: "Jammu & Kashmir",    value: 889 },
      { state: "NCT of Delhi",       value: 868 },
      { state: "Sikkim",             value: 890 },
      { state: "Nagaland",           value: 931 },
      { state: "Jharkhand",          value: 948 },
      { state: "Madhya Pradesh",     value: 931 },
      { state: "Goa",                value: 973 },
      { state: "Arunanchal Pradesh", value: 938 },
    ],
  },

  // ── Health ───────────────────────────────────────────────────────────
  "india-life-expectancy": {
    indicatorId: "india-life-expectancy",
    indicatorName: "Life Expectancy",
    unit: "years",
    year: 2020,
    source: "SRS Statistical Report 2020",
    rows: [
      { state: "Kerala",             value: 75.2 },
      { state: "NCT of Delhi",       value: 73.1 },
      { state: "Jammu & Kashmir",    value: 73.8 },
      { state: "Puducherry",         value: 73.5 },
      { state: "Goa",                value: 73.5 },
      { state: "Himachal Pradesh",   value: 72.0 },
      { state: "Punjab",             value: 72.7 },
      { state: "Manipur",            value: 72.3 },
      { state: "Nagaland",           value: 71.3 },
      { state: "Tamil Nadu",         value: 71.4 },
      { state: "Mizoram",            value: 70.1 },
      { state: "Sikkim",             value: 70.5 },
      { state: "West Bengal",        value: 70.2 },
      { state: "Maharashtra",        value: 71.2 },
      { state: "Tripura",            value: 69.8 },
      { state: "Andhra Pradesh",     value: 69.8 },
      { state: "Telangana",          value: 69.5 },
      { state: "Karnataka",          value: 69.9 },
      { state: "Uttarakhand",        value: 69.3 },
      { state: "Haryana",            value: 69.0 },
      { state: "Arunanchal Pradesh", value: 68.0 },
      { state: "Gujarat",            value: 68.7 },
      { state: "Bihar",              value: 68.1 },
      { state: "Odisha",             value: 68.5 },
      { state: "Meghalaya",          value: 66.7 },
      { state: "Jharkhand",          value: 66.4 },
      { state: "Rajasthan",          value: 67.8 },
      { state: "Madhya Pradesh",     value: 65.5 },
      { state: "Chhattisgarh",       value: 65.2 },
      { state: "Assam",              value: 64.9 },
      { state: "Uttar Pradesh",      value: 64.5 },
    ],
  },

  "india-infant-mortality": {
    indicatorId: "india-infant-mortality",
    indicatorName: "Infant Mortality Rate",
    unit: "per 1,000 births",
    year: 2021,
    source: "NFHS-5 (2019-21)",
    rows: [
      { state: "Sikkim",             value: 5.5 },
      { state: "Kerala",             value: 5.6 },
      { state: "Goa",                value: 6.4 },
      { state: "Nagaland",           value: 7.2 },
      { state: "Manipur",            value: 7.8 },
      { state: "Mizoram",            value: 7.8 },
      { state: "NCT of Delhi",       value: 10.9 },
      { state: "Puducherry",         value: 11.3 },
      { state: "Himachal Pradesh",   value: 19.5 },
      { state: "Karnataka",          value: 19.5 },
      { state: "Maharashtra",        value: 20.8 },
      { state: "Jammu & Kashmir",    value: 17.1 },
      { state: "Tamil Nadu",         value: 15.2 },
      { state: "Punjab",             value: 22.1 },
      { state: "Gujarat",            value: 24.4 },
      { state: "Tripura",            value: 23.1 },
      { state: "Andhra Pradesh",     value: 26.4 },
      { state: "Telangana",          value: 26.7 },
      { state: "Uttarakhand",        value: 27.5 },
      { state: "Haryana",            value: 29.0 },
      { state: "West Bengal",        value: 22.6 },
      { state: "Meghalaya",          value: 30.3 },
      { state: "Arunanchal Pradesh", value: 29.5 },
      { state: "Odisha",             value: 32.6 },
      { state: "Rajasthan",          value: 35.0 },
      { state: "Jharkhand",          value: 35.8 },
      { state: "Uttar Pradesh",      value: 37.6 },
      { state: "Assam",              value: 38.4 },
      { state: "Chhattisgarh",       value: 38.9 },
      { state: "Madhya Pradesh",     value: 43.2 },
      { state: "Bihar",              value: 45.8 },
    ],
  },

  "india-stunting": {
    indicatorId: "india-stunting",
    indicatorName: "Child Stunting",
    unit: "%",
    year: 2021,
    source: "NFHS-5 (2019-21)",
    rows: [
      { state: "Kerala",             value: 23.4 },
      { state: "Goa",                value: 25.8 },
      { state: "Sikkim",             value: 22.3 },
      { state: "Manipur",            value: 28.9 },
      { state: "Mizoram",            value: 27.6 },
      { state: "NCT of Delhi",       value: 32.0 },
      { state: "Punjab",             value: 24.5 },
      { state: "Himachal Pradesh",   value: 26.9 },
      { state: "Tamil Nadu",         value: 27.1 },
      { state: "Telangana",          value: 33.1 },
      { state: "Karnataka",          value: 35.4 },
      { state: "Maharashtra",        value: 35.2 },
      { state: "Andhra Pradesh",     value: 31.4 },
      { state: "Gujarat",            value: 39.7 },
      { state: "Haryana",            value: 27.1 },
      { state: "Rajasthan",          value: 31.8 },
      { state: "West Bengal",        value: 33.8 },
      { state: "Odisha",             value: 34.1 },
      { state: "Assam",              value: 35.7 },
      { state: "Madhya Pradesh",     value: 40.0 },
      { state: "Jharkhand",          value: 40.3 },
      { state: "Bihar",              value: 42.9 },
      { state: "Uttar Pradesh",      value: 39.7 },
      { state: "Chhattisgarh",       value: 37.6 },
      { state: "Uttarakhand",        value: 28.1 },
      { state: "Jammu & Kashmir",    value: 27.7 },
      { state: "Tripura",            value: 32.8 },
      { state: "Meghalaya",          value: 46.5 },
      { state: "Arunanchal Pradesh", value: 32.0 },
      { state: "Nagaland",           value: 28.6 },
    ],
  },

  "india-anaemia-women": {
    indicatorId: "india-anaemia-women",
    indicatorName: "Anaemia in Women",
    unit: "%",
    year: 2021,
    source: "NFHS-5 (2019-21)",
    rows: [
      { state: "Assam",              value: 68.3 },
      { state: "Gujarat",            value: 65.5 },
      { state: "West Bengal",        value: 66.9 },
      { state: "Jharkhand",          value: 65.4 },
      { state: "Uttar Pradesh",      value: 59.0 },
      { state: "Madhya Pradesh",     value: 54.7 },
      { state: "Bihar",              value: 63.5 },
      { state: "Rajasthan",          value: 55.9 },
      { state: "Odisha",             value: 63.0 },
      { state: "Haryana",            value: 59.8 },
      { state: "Chhattisgarh",       value: 57.9 },
      { state: "NCT of Delhi",       value: 52.4 },
      { state: "Andhra Pradesh",     value: 59.7 },
      { state: "Telangana",          value: 56.5 },
      { state: "Karnataka",          value: 48.8 },
      { state: "Maharashtra",        value: 48.7 },
      { state: "Tamil Nadu",         value: 45.3 },
      { state: "Punjab",             value: 53.5 },
      { state: "Himachal Pradesh",   value: 45.4 },
      { state: "Kerala",             value: 35.7 },
      { state: "Uttarakhand",        value: 47.8 },
      { state: "Jammu & Kashmir",    value: 46.2 },
      { state: "Goa",                value: 37.9 },
      { state: "Tripura",            value: 71.7 },
      { state: "Manipur",            value: 37.2 },
      { state: "Meghalaya",          value: 56.1 },
      { state: "Mizoram",            value: 40.5 },
      { state: "Nagaland",           value: 28.0 },
      { state: "Arunanchal Pradesh", value: 42.8 },
      { state: "Sikkim",             value: 41.4 },
    ],
  },

  // ── Education ────────────────────────────────────────────────────────
  "india-literacy": {
    indicatorId: "india-literacy",
    indicatorName: "Literacy Rate",
    unit: "%",
    year: 2011,
    source: "Census 2011",
    rows: [
      { state: "Kerala",             value: 94.0 },
      { state: "Lakshadweep",        value: 92.3 },
      { state: "Mizoram",            value: 91.6 },
      { state: "Goa",                value: 88.7 },
      { state: "Tripura",            value: 87.8 },
      { state: "Puducherry",         value: 86.6 },
      { state: "NCT of Delhi",       value: 86.3 },
      { state: "Chandigarh",         value: 86.1 },
      { state: "Himachal Pradesh",   value: 83.8 },
      { state: "Uttarakhand",        value: 79.6 },
      { state: "Gujarat",            value: 79.3 },
      { state: "Nagaland",           value: 80.1 },
      { state: "Tamil Nadu",         value: 80.1 },
      { state: "Manipur",            value: 79.9 },
      { state: "Sikkim",             value: 82.2 },
      { state: "Maharashtra",        value: 82.9 },
      { state: "West Bengal",        value: 77.1 },
      { state: "Meghalaya",          value: 75.5 },
      { state: "Punjab",             value: 76.7 },
      { state: "Haryana",            value: 76.6 },
      { state: "Karnataka",          value: 75.6 },
      { state: "Assam",              value: 73.2 },
      { state: "Odisha",             value: 73.5 },
      { state: "Chhattisgarh",       value: 71.0 },
      { state: "Madhya Pradesh",     value: 70.6 },
      { state: "Uttar Pradesh",      value: 67.7 },
      { state: "Rajasthan",          value: 67.1 },
      { state: "Jharkhand",          value: 67.6 },
      { state: "Jammu & Kashmir",    value: 68.7 },
      { state: "Andhra Pradesh",     value: 67.4 },
      { state: "Telangana",          value: 66.5 },
      { state: "Arunanchal Pradesh", value: 66.9 },
      { state: "Bihar",              value: 63.8 },
    ],
  },

  "india-female-literacy": {
    indicatorId: "india-female-literacy",
    indicatorName: "Female Literacy Rate",
    unit: "%",
    year: 2011,
    source: "Census 2011",
    rows: [
      { state: "Kerala",             value: 92.1 },
      { state: "Mizoram",            value: 89.4 },
      { state: "Goa",                value: 84.7 },
      { state: "Tripura",            value: 83.1 },
      { state: "Puducherry",         value: 81.2 },
      { state: "NCT of Delhi",       value: 80.9 },
      { state: "Himachal Pradesh",   value: 76.6 },
      { state: "Uttarakhand",        value: 70.7 },
      { state: "Tamil Nadu",         value: 73.9 },
      { state: "Manipur",            value: 73.2 },
      { state: "Nagaland",           value: 76.7 },
      { state: "Maharashtra",        value: 75.5 },
      { state: "Sikkim",             value: 75.6 },
      { state: "West Bengal",        value: 71.2 },
      { state: "Meghalaya",          value: 73.8 },
      { state: "Gujarat",            value: 70.7 },
      { state: "Punjab",             value: 71.3 },
      { state: "Haryana",            value: 66.8 },
      { state: "Karnataka",          value: 68.1 },
      { state: "Odisha",             value: 64.4 },
      { state: "Assam",              value: 67.3 },
      { state: "Andhra Pradesh",     value: 59.7 },
      { state: "Madhya Pradesh",     value: 60.0 },
      { state: "Chhattisgarh",       value: 60.6 },
      { state: "Uttar Pradesh",      value: 59.3 },
      { state: "Jammu & Kashmir",    value: 58.0 },
      { state: "Jharkhand",          value: 56.2 },
      { state: "Rajasthan",          value: 52.7 },
      { state: "Arunanchal Pradesh", value: 59.0 },
      { state: "Bihar",              value: 53.3 },
    ],
  },

  "india-school-dropout": {
    indicatorId: "india-school-dropout",
    indicatorName: "School Dropout Rate",
    unit: "%",
    year: 2022,
    source: "UDISE+ 2021-22",
    rows: [
      { state: "Assam",              value: 28.1 },
      { state: "Bihar",              value: 18.2 },
      { state: "Meghalaya",          value: 25.8 },
      { state: "Arunanchal Pradesh", value: 24.3 },
      { state: "Odisha",             value: 18.8 },
      { state: "Rajasthan",          value: 17.9 },
      { state: "Nagaland",           value: 22.0 },
      { state: "Jharkhand",          value: 19.5 },
      { state: "West Bengal",        value: 14.5 },
      { state: "Uttar Pradesh",      value: 15.3 },
      { state: "Madhya Pradesh",     value: 14.9 },
      { state: "Chhattisgarh",       value: 14.3 },
      { state: "Manipur",            value: 16.8 },
      { state: "Tripura",            value: 11.4 },
      { state: "Andhra Pradesh",     value: 11.8 },
      { state: "Haryana",            value: 9.2 },
      { state: "Gujarat",            value: 9.7 },
      { state: "Maharashtra",        value: 8.4 },
      { state: "Karnataka",          value: 9.9 },
      { state: "Telangana",          value: 10.5 },
      { state: "Tamil Nadu",         value: 5.1 },
      { state: "Punjab",             value: 7.3 },
      { state: "Himachal Pradesh",   value: 5.6 },
      { state: "Kerala",             value: 1.1 },
      { state: "Uttarakhand",        value: 6.3 },
      { state: "NCT of Delhi",       value: 4.2 },
      { state: "Goa",                value: 3.5 },
      { state: "Jammu & Kashmir",    value: 6.2 },
      { state: "Sikkim",             value: 5.8 },
      { state: "Mizoram",            value: 6.1 },
    ],
  },

  // ── Environment ──────────────────────────────────────────────────────
  "india-forest-cover": {
    indicatorId: "india-forest-cover",
    indicatorName: "Forest Cover",
    unit: "%",
    year: 2021,
    source: "FSI State of Forest Report 2021",
    rows: [
      { state: "Mizoram",            value: 84.5 },
      { state: "Arunanchal Pradesh", value: 79.3 },
      { state: "Meghalaya",          value: 75.9 },
      { state: "Manipur",            value: 74.3 },
      { state: "Nagaland",           value: 73.0 },
      { state: "Tripura",            value: 72.0 },
      { state: "Sikkim",             value: 81.2 },
      { state: "Goa",                value: 55.6 },
      { state: "Andaman & Nicobar Island", value: 91.6 },
      { state: "Kerala",             value: 52.3 },
      { state: "Chhattisgarh",       value: 41.1 },
      { state: "Uttarakhand",        value: 45.4 },
      { state: "Odisha",             value: 33.1 },
      { state: "Jharkhand",          value: 33.4 },
      { state: "Andhra Pradesh",     value: 27.0 },
      { state: "Telangana",          value: 24.8 },
      { state: "Karnataka",          value: 21.3 },
      { state: "Madhya Pradesh",     value: 25.1 },
      { state: "Assam",              value: 35.3 },
      { state: "Maharashtra",        value: 20.8 },
      { state: "West Bengal",        value: 19.0 },
      { state: "Himachal Pradesh",   value: 27.7 },
      { state: "Jammu & Kashmir",    value: 10.2 },
      { state: "Rajasthan",          value: 4.8 },
      { state: "Tamil Nadu",         value: 20.0 },
      { state: "Gujarat",            value: 7.5 },
      { state: "Uttar Pradesh",      value: 6.1 },
      { state: "Bihar",              value: 7.7 },
      { state: "Haryana",            value: 3.6 },
      { state: "Punjab",             value: 3.7 },
      { state: "NCT of Delhi",       value: 11.2 },
    ],
  },

  "india-groundwater-level": {
    indicatorId: "india-groundwater-level",
    indicatorName: "Groundwater Extraction",
    unit: "%",
    year: 2022,
    source: "CGWB 2022",
    rows: [
      { state: "Punjab",             value: 166.0 },
      { state: "Rajasthan",          value: 141.0 },
      { state: "Haryana",            value: 137.0 },
      { state: "NCT of Delhi",       value: 122.0 },
      { state: "Uttar Pradesh",      value: 74.0 },
      { state: "Tamil Nadu",         value: 77.0 },
      { state: "Gujarat",            value: 64.0 },
      { state: "Bihar",              value: 42.0 },
      { state: "Andhra Pradesh",     value: 55.0 },
      { state: "Karnataka",          value: 63.0 },
      { state: "Maharashtra",        value: 52.0 },
      { state: "Madhya Pradesh",     value: 61.0 },
      { state: "Telangana",          value: 57.0 },
      { state: "West Bengal",        value: 36.0 },
      { state: "Kerala",             value: 47.0 },
      { state: "Odisha",             value: 26.0 },
      { state: "Chhattisgarh",       value: 22.0 },
      { state: "Jharkhand",          value: 23.0 },
      { state: "Assam",              value: 18.0 },
      { state: "Uttarakhand",        value: 35.0 },
      { state: "Himachal Pradesh",   value: 20.0 },
      { state: "Jammu & Kashmir",    value: 28.0 },
      { state: "Arunanchal Pradesh", value: 8.0 },
      { state: "Meghalaya",          value: 12.0 },
      { state: "Manipur",            value: 14.0 },
      { state: "Mizoram",            value: 10.0 },
      { state: "Nagaland",           value: 11.0 },
      { state: "Sikkim",             value: 7.0 },
      { state: "Tripura",            value: 21.0 },
      { state: "Goa",                value: 39.0 },
    ],
  },

  // ── Governance ───────────────────────────────────────────────────────
  "india-hdi": {
    indicatorId: "india-hdi",
    indicatorName: "Human Development Index",
    unit: "score",
    year: 2022,
    source: "NITI Aayog / UNDP 2022",
    rows: [
      { state: "Kerala",             value: 0.779 },
      { state: "Goa",                value: 0.761 },
      { state: "Sikkim",             value: 0.716 },
      { state: "Himachal Pradesh",   value: 0.725 },
      { state: "Punjab",             value: 0.723 },
      { state: "Tamil Nadu",         value: 0.708 },
      { state: "Mizoram",            value: 0.705 },
      { state: "Uttarakhand",        value: 0.684 },
      { state: "Manipur",            value: 0.682 },
      { state: "Karnataka",          value: 0.682 },
      { state: "Maharashtra",        value: 0.696 },
      { state: "Jammu & Kashmir",    value: 0.688 },
      { state: "Andhra Pradesh",     value: 0.649 },
      { state: "Telangana",          value: 0.656 },
      { state: "Haryana",            value: 0.658 },
      { state: "Tripura",            value: 0.658 },
      { state: "Gujarat",            value: 0.672 },
      { state: "West Bengal",        value: 0.641 },
      { state: "Nagaland",           value: 0.679 },
      { state: "Meghalaya",          value: 0.638 },
      { state: "Arunanchal Pradesh", value: 0.621 },
      { state: "Rajasthan",          value: 0.629 },
      { state: "Assam",              value: 0.614 },
      { state: "Chhattisgarh",       value: 0.613 },
      { state: "Odisha",             value: 0.606 },
      { state: "Madhya Pradesh",     value: 0.603 },
      { state: "Uttar Pradesh",      value: 0.596 },
      { state: "Bihar",              value: 0.574 },
      { state: "Jharkhand",          value: 0.599 },
      { state: "NCT of Delhi",       value: 0.746 },
    ],
  },

  "india-sdg-index": {
    indicatorId: "india-sdg-index",
    indicatorName: "SDG Index Score",
    unit: "score",
    year: 2023,
    source: "NITI Aayog SDG Index 2023-24",
    rows: [
      { state: "Kerala",             value: 79 },
      { state: "Uttarakhand",        value: 76 },
      { state: "Tamil Nadu",         value: 78 },
      { state: "Goa",                value: 75 },
      { state: "Himachal Pradesh",   value: 74 },
      { state: "Sikkim",             value: 75 },
      { state: "Chandigarh",         value: 79 },
      { state: "NCT of Delhi",       value: 68 },
      { state: "Karnataka",          value: 72 },
      { state: "Andhra Pradesh",     value: 67 },
      { state: "Telangana",          value: 68 },
      { state: "Gujarat",            value: 67 },
      { state: "Maharashtra",        value: 67 },
      { state: "Punjab",             value: 63 },
      { state: "Mizoram",            value: 70 },
      { state: "Manipur",            value: 68 },
      { state: "Nagaland",           value: 66 },
      { state: "Haryana",            value: 66 },
      { state: "West Bengal",        value: 66 },
      { state: "Tripura",            value: 72 },
      { state: "Rajasthan",          value: 60 },
      { state: "Odisha",             value: 63 },
      { state: "Madhya Pradesh",     value: 58 },
      { state: "Assam",              value: 63 },
      { state: "Chhattisgarh",       value: 62 },
      { state: "Jharkhand",          value: 61 },
      { state: "Uttar Pradesh",      value: 60 },
      { state: "Arunanchal Pradesh", value: 68 },
      { state: "Bihar",              value: 57 },
      { state: "Meghalaya",          value: 66 },
      { state: "Jammu & Kashmir",    value: 66 },
    ],
  },

  "india-crime-rate": {
    indicatorId: "india-crime-rate",
    indicatorName: "Crime Rate (IPC)",
    unit: "per lakh",
    year: 2022,
    source: "NCRB 2022",
    rows: [
      { state: "NCT of Delhi",       value: 1586.4 },
      { state: "Rajasthan",          value: 626.7 },
      { state: "Kerala",             value: 574.4 },
      { state: "Madhya Pradesh",     value: 367.3 },
      { state: "Telangana",          value: 344.6 },
      { state: "Assam",              value: 355.2 },
      { state: "Odisha",             value: 328.8 },
      { state: "Haryana",            value: 313.5 },
      { state: "Uttarakhand",        value: 289.3 },
      { state: "Chhattisgarh",       value: 286.4 },
      { state: "Andhra Pradesh",     value: 268.9 },
      { state: "Maharashtra",        value: 271.6 },
      { state: "Karnataka",          value: 232.5 },
      { state: "Jharkhand",          value: 221.3 },
      { state: "West Bengal",        value: 174.5 },
      { state: "Punjab",             value: 182.8 },
      { state: "Gujarat",            value: 158.3 },
      { state: "Tamil Nadu",         value: 218.8 },
      { state: "Uttar Pradesh",      value: 157.2 },
      { state: "Bihar",              value: 136.6 },
      { state: "Jammu & Kashmir",    value: 142.4 },
      { state: "Himachal Pradesh",   value: 147.3 },
      { state: "Goa",                value: 359.2 },
      { state: "Tripura",            value: 198.4 },
      { state: "Manipur",            value: 112.3 },
      { state: "Meghalaya",          value: 124.5 },
      { state: "Mizoram",            value: 74.8 },
      { state: "Nagaland",           value: 53.6 },
      { state: "Sikkim",             value: 95.4 },
      { state: "Arunanchal Pradesh", value: 158.7 },
    ],
  },
};

/**
 * GET /api/india-data?id=india-gsdp
 * Returns curated India state-level data for the given indicator ID.
 */
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const id = searchParams.get("id");

  if (!id) {
    return NextResponse.json({ error: "Missing id parameter" }, { status: 400 });
  }

  const dataset = DATASETS[id];
  if (!dataset) {
    return NextResponse.json(
      { error: `Unknown India indicator: ${id}. Available: ${Object.keys(DATASETS).join(", ")}` },
      { status: 404 }
    );
  }

  return NextResponse.json(dataset, {
    headers: {
      // Cache for 24 hours — data doesn't change often
      "Cache-Control": "public, s-maxage=86400, stale-while-revalidate=604800",
    },
  });
}
